//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TileIconifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TileIconifier.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abord.
        /// </summary>
        internal static string Abord {
            get {
                return ResourceManager.GetString("Abord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Bottom.
        /// </summary>
        internal static string AlignBottom {
            get {
                return ResourceManager.GetString("AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Centre.
        /// </summary>
        internal static string AlignCentre {
            get {
                return ResourceManager.GetString("AlignCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Image.
        /// </summary>
        internal static string AlignImage {
            get {
                return ResourceManager.GetString("AlignImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left.
        /// </summary>
        internal static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        internal static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Top.
        /// </summary>
        internal static string AlignTop {
            get {
                return ResourceManager.GetString("AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align X Middle.
        /// </summary>
        internal static string AlignXMiddle {
            get {
                return ResourceManager.GetString("AlignXMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Y Middle.
        /// </summary>
        internal static string AlignYMiddle {
            get {
                return ResourceManager.GetString("AlignYMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already on the latest version!.
        /// </summary>
        internal static string AlreadyLatest {
            get {
                return ResourceManager.GetString("AlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Id.
        /// </summary>
        internal static string AppId {
            get {
                return ResourceManager.GetString("AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Too Early.
        /// </summary>
        internal static string BuildTooEarly {
            get {
                return ResourceManager.GetString("BuildTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre Image.
        /// </summary>
        internal static string CentreImage {
            get {
                return ResourceManager.GetString("CentreImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        internal static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Chrome `Extensions` folder.
        /// </summary>
        internal static string ChromeExtensionsFolder {
            get {
                return ResourceManager.GetString("ChromeExtensionsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the custom shortcut for {0}?.
        /// </summary>
        internal static string ConfirmDeleteCustomShortcut {
            get {
                return ResourceManager.GetString("ConfirmDeleteCustomShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove iconification?.
        /// </summary>
        internal static string ConfirmRemoveIconification {
            get {
                return ResourceManager.GetString("ConfirmRemoveIconification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        internal static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations for this application will NEVER be required but would be greatly appreciated. This application will ALWAYS be free, open source, and supported to the best of my ability. If you would like to help support me with this and future applications I would be very grateful!
        ///
        ///Do you wish to proceed to the donation page (https://www.paypal.me/Jonno12345)?.
        /// </summary>
        internal static string DonationNotification {
            get {
                return ResourceManager.GetString("DonationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to load this image file! Please try another..
        /// </summary>
        internal static string ErrorLoadingImageFile {
            get {
                return ResourceManager.GetString("ErrorLoadingImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be found.
        /// </summary>
        internal static string FileCouldNotBeFound {
            get {
                return ResourceManager.GetString("FileCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Colour Change.
        /// </summary>
        internal static string ForegroundColourChange {
            get {
                return ResourceManager.GetString("ForegroundColourChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground colour changes don&apos;t always instantly apply. If this change hasn&apos;t applied, try unpinning and repinning the shortcut..
        /// </summary>
        internal static string ForegroundColourChangeExplain {
            get {
                return ResourceManager.GetString("ForegroundColourChangeExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        internal static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon error.
        /// </summary>
        internal static string IconError {
            get {
                return ResourceManager.GetString("IconError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Platform.
        /// </summary>
        internal static string IncorrectPlatform {
            get {
                return ResourceManager.GetString("IncorrectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running as a 32-bit process within a 64-bit operating system. Certain functionality, such as powershell, may not work correctly..
        /// </summary>
        internal static string IncorrectPlatformFull {
            get {
                return ResourceManager.GetString("IncorrectPlatformFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters or invalid shortcut name!.
        /// </summary>
        internal static string InvalidCharactersOrInvalidShortcutName {
            get {
                return ResourceManager.GetString("InvalidCharactersOrInvalidShortcutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder is invalid (valid folders should contain a subfolder named &quot;steamapps&quot;), please try again or cancel..
        /// </summary>
        internal static string InvalidSteamLibraryPath {
            get {
                return ResourceManager.GetString("InvalidSteamLibraryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Custom.
        /// </summary>
        internal static string IsCustom {
            get {
                return ResourceManager.GetString("IsCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Iconified.
        /// </summary>
        internal static string IsIconified {
            get {
                return ResourceManager.GetString("IsIconified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Pinned.
        /// </summary>
        internal static string IsPinned {
            get {
                return ResourceManager.GetString("IsPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue occurred with the image selected. Please load the icon again or try another..
        /// </summary>
        internal static string IssueWithImageSelected {
            get {
                return ResourceManager.GetString("IssueWithImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No icon has been selected!.
        /// </summary>
        internal static string NoIconHasBeenSelected {
            get {
                return ResourceManager.GetString("NoIconHasBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items have been selected!.
        /// </summary>
        internal static string NoItemsHaveBeenSelected {
            get {
                return ResourceManager.GetString("NoItemsHaveBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Down.
        /// </summary>
        internal static string NudgeDown {
            get {
                return ResourceManager.GetString("NudgeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Left.
        /// </summary>
        internal static string NudgeLeft {
            get {
                return ResourceManager.GetString("NudgeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Right.
        /// </summary>
        internal static string NudgeRight {
            get {
                return ResourceManager.GetString("NudgeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge Up.
        /// </summary>
        internal static string NudgeUp {
            get {
                return ResourceManager.GetString("NudgeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string PanPctLine1 {
            get {
                return ResourceManager.GetString("PanPctLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string PanPctLine2 {
            get {
                return ResourceManager.GetString("PanPctLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        internal static string PanPctLine3 {
            get {
                return ResourceManager.GetString("PanPctLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not found.
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an icon.
        /// </summary>
        internal static string PleaseSelectAnIcon {
            get {
                return ResourceManager.GetString("PleaseSelectAnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred with PowerShell functionality. It has been disabled..
        /// </summary>
        internal static string PowershellErrorFull {
            get {
                return ResourceManager.GetString("PowershellErrorFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell failure.
        /// </summary>
        internal static string PowershellFailure {
            get {
                return ResourceManager.GetString("PowershellFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will create a custom shortcut with the same parameters as {0}. This is useful for tiles that don&apos;t work by default (Such as Microsoft Office and Mozilla Firefox). Please confirm the name for the new shortcut (The same name as the original is not a problem).
        /// </summary>
        internal static string QuickBuildExplanation {
            get {
                return ResourceManager.GetString("QuickBuildExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing.
        /// </summary>
        internal static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        internal static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must run this application as an Administrator!.
        /// </summary>
        internal static string RunAsAdminFull {
            get {
                return ResourceManager.GetString("RunAsAdminFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder.
        /// </summary>
        internal static string SelectAFolder {
            get {
                return ResourceManager.GetString("SelectAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder containing your Steam installation.
        /// </summary>
        internal static string SelectSteamInstallationPath {
            get {
                return ResourceManager.GetString("SelectSteamInstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder containing your Steam library (This will be a folder containing a &quot;steamapps&quot; folder).
        /// </summary>
        internal static string SelectSteamLibraryPath {
            get {
                return ResourceManager.GetString("SelectSteamLibraryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid color!.
        /// </summary>
        internal static string SelectValidColor {
            get {
                return ResourceManager.GetString("SelectValidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut created!.
        /// </summary>
        internal static string ShortcutCreated {
            get {
                return ResourceManager.GetString("ShortcutCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shortcut for {0} has been created in your start menu under TileIconify. The item will need to be pinned manually..
        /// </summary>
        internal static string ShortcutCreatedNeedsPinning {
            get {
                return ResourceManager.GetString("ShortcutCreatedNeedsPinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Name.
        /// </summary>
        internal static string ShortcutName {
            get {
                return ResourceManager.GetString("ShortcutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Type.
        /// </summary>
        internal static string ShortcutType {
            get {
                return ResourceManager.GetString("ShortcutType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut User.
        /// </summary>
        internal static string ShortcutUser {
            get {
                return ResourceManager.GetString("ShortcutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam executable path.
        /// </summary>
        internal static string SteamExecutablePath {
            get {
                return ResourceManager.GetString("SteamExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam executable path not found!!!.
        /// </summary>
        internal static string SteamExecutablePathNotFound {
            get {
                return ResourceManager.GetString("SteamExecutablePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam installation path.
        /// </summary>
        internal static string SteamInstallationPath {
            get {
                return ResourceManager.GetString("SteamInstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam installation path not found!!!.
        /// </summary>
        internal static string SteamInstallationPathNotFound {
            get {
                return ResourceManager.GetString("SteamInstallationPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam library folders.
        /// </summary>
        internal static string SteamLibraryFolders {
            get {
                return ResourceManager.GetString("SteamLibraryFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam library paths not found!!!.
        /// </summary>
        internal static string SteamLibraryFoldersNotFound {
            get {
                return ResourceManager.GetString("SteamLibraryFoldersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target path is empty!.
        /// </summary>
        internal static string TargetPathIsEmpty {
            get {
                return ResourceManager.GetString("TargetPathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check server!.
        /// </summary>
        internal static string UnableToCheckServer {
            get {
                return ResourceManager.GetString("UnableToCheckServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clear up shortcuts..
        /// </summary>
        internal static string UnableToClearShortcuts {
            get {
                return ResourceManager.GetString("UnableToClearShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clear up shortcuts..
        /// </summary>
        internal static string UnableToClearUpShortcuts {
            get {
                return ResourceManager.GetString("UnableToClearUpShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Chrome installation path!.
        /// </summary>
        internal static string UnableToFindChromeInstallationPath {
            get {
                return ResourceManager.GetString("UnableToFindChromeInstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred getting latest release information. Click Ok to visit the latest releases page to check manually. (Your version: {0}).
        /// </summary>
        internal static string UpdateAvailableError {
            get {
                return ResourceManager.GetString("UpdateAvailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available! Would you like to visit the releases page? (Your version: {0} - Latest version: {1}).
        /// </summary>
        internal static string UpdateAvailableFull {
            get {
                return ResourceManager.GetString("UpdateAvailableFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note- This feature uses Powershell and may take slightly longer to refresh. Continue?.
        /// </summary>
        internal static string UsesPowershell {
            get {
                return ResourceManager.GetString("UsesPowershell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Administrator.
        /// </summary>
        internal static string VerifyAdmin {
            get {
                return ResourceManager.GetString("VerifyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred detecting administrator state. Please verify you are running as an administrator, or issues may occur..
        /// </summary>
        internal static string VerifyAdminFull {
            get {
                return ResourceManager.GetString("VerifyAdminFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on a version of Windows earlier than 8.1, changes might not take any effect..
        /// </summary>
        internal static string WindowsBefore81 {
            get {
                return ResourceManager.GetString("WindowsBefore81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows version too early.
        /// </summary>
        internal static string WindowsTooEarly {
            get {
                return ResourceManager.GetString("WindowsTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running Windows 10, but not on or above Build 10586. The program will run, but some changes may not take effect..
        /// </summary>
        internal static string WrongBuildWindows10 {
            get {
                return ResourceManager.GetString("WrongBuildWindows10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
